modLoader="javafml"
loaderVersion="[36,)"
license="GNU GENERAL PUBLIC LICENSE V3"
issueTrackerURL="https://github.com/VulpTheHorseDog/Tomes/issues/"
[[mods]]
modId="tomes"
version="1.0"
displayName="Tomes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/tomes/"
# logoFile="examplemod.png"
credits="Big thanks to Dandrawer who commissioned this mod!"
authors="VulpTheHorseDog"
description='''
A tome-based magic mod where you can enchant the tomes for different active and passive effects!
'''
[[dependencies.tomes]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
